apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
    rules:
        - http:
            paths:
                - path: /api/users/?(.*)
                  backend:
                    serviceName: auth-srv
                    servicePort: 3000
                - path: /api/activity-recorder/?(.*)
                  backend:
                      serviceName: activity-recorder-srv
                      servicePort: 3000
                - path: /api/users/profile/?(.*)
                  backend:
                      serviceName: profile-srv
                      servicePort: 3000
                - path: /api/swagger/docs
                  backend:
                      serviceName: swagger-srv
                      servicePort: 3000
                - path: /?(.*)
                  backend:
                      serviceName: client-srv
                      servicePort: 3000
